version: "3"
services:
    frontend:
        build: 
         context: .
        image: frontend
       networks:
             - allnetwork
     
networks:
    default:
       external:
          name: allnetwork