version: "3"
services:
    frontend:
        build: 
        context: .
        image: frontend
        networks:
            - intregrated-network
networks:
    intregrated-network:
       external: true